- hosts: web
  tasks:
  - name: enable php7.4
    shell:  amazon-linux-extras enable php7.4
    become: yes

  - name: enable python3.8
    shell:  amazon-linux-extras enable python3.8
    become: yes

  - name: enable ansible2
    shell:  amazon-linux-extras enable ansible2
    become: yes

  - name: clean metadata
    shell:  yum clean metadata
    become: yes

  - name: install php-cli
    yum:
      name: php-cli 
      state: latest

  - name: install php-pdo
    yum:
      name: php-pdo
      state: latest

  - name: install php-fpm
    yum:
      name: php-fpm  
      state: latest

  - name: install php-json
    yum:
      name: php-json
      state: latest

  - name: install php-mysqlnd
    yum:
      name: php-mysqlnd
      state: latest
 
  - name: install python3.8
    yum:
      name: python3.8
      state: latest
      become: yes
      update_cache: yes        

  - name: install MySQL-python
    yum:
      name: MySQL-python
      state: latest
      become: yes
      update_cache: yes
  
