- hosts: web
  tasks:
  - name: enable php7.4
    shell:  amazon-linux-extras enable php7.4
    become: yes

  - name: enable python3.8
    shell:  amazon-linux-extras enable python3.8
    become: yes

  - name: enable ansible2
    shell:  amazon-linux-extras enable ansible2
    become: yes

  - name: clean metadata
    shell:  yum clean metadata
    become: yes

  - name: install php-cli
    yum:
      name: php-cli 
      state: latest

  - name: install php-pdo
    yum:
      name: php-pdo
      state: latest

  - name: install php-fpm
    yum:
      name: php-fpm  
      state: latest

  - name: install php-json
    yum:
      name: php-json
      state: latest

  - name: install php-mysqlnd
    yum:
      name: php-mysqlnd
      state: latest

  - name: install python-libs
    yum:
      name:  python38-libs
      state: latest

  - name: install python-pip
    yum:
      name:  python38-pip
      state: latest

  - name: install python38-setuptools
    yum:
      name:  python38-setuptools
      state: latest

  - name: install python38
    yum:
      name:  python38
      state: latest
   

  - name: install MySQL-python
    yum:
      name:  MySQL-python
      state: latest

- hosts: web
  tasks:
  - name: Install client
    yum:
      name: mariadb
      state: latest

- hosts: web
  tasks:
  - name: Install Mysql
    yum:
      name: mariadb-server
      state: latest

  - name: Start mariadb
    systemd:
      name: mariadb
      state: started

  - name: Enable mariadb
    become: yes
    shell: "systemctl enable mariadb"
      
  - name: Restart  mariadb
    become: yes
    shell: "systemctl restart mariadb"
