- hosts: db
  tasks:
  - name: Inst
    yum:
      name:
           - mysql-devel
           - centos-release-scl
      state: present

- hosts: db
  tasks:
  - name: Install MySQl
    yum:
      name: mariadb
      state: latest
- hosts: db
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "12345678"
  tasks:
  - name: Install Mysql
    yum:
      name: mariadb-server
      state: latest

  - name: Start mariadb
    systemd:
      name: mariadb
      state: started

  - name: Enable mariadb
    systemd:
      name: mariadb
      enabled: yes
      masked: no
  - name: mysql_root_password
    mysql_user:
      login_user: wordpress
      login_password: "12345678"
      user: admin
      check_implicit_admin: true
      password: "12345678"







